import os

# __all__ = [i[:-len('.py')] for i in os.listdir('census_processor/') if i.endswith('.py') and (not i.startswith('_'))]

from census_processor.argentina import Argentina
from census_processor.australia import Australia
from census_processor.austria import Austria
from census_processor.belgium import Belgium
from census_processor.brazil import Brazil
from census_processor.bulgaria import Bulgaria
from census_processor.canada import Canada
from census_processor.china import China
from census_processor.croatia import Croatia
from census_processor.cyprus import Cyprus
from census_processor.czechia import Czechia
from census_processor.denmark import Denmark
from census_processor.estonia import Estonia
from census_processor.ethiopia import Ethiopia
from census_processor.finland import Finland
from census_processor.france import France
from census_processor.germany import Germany
from census_processor.world import World
from census_processor.greece import Greece
from census_processor.hungary import Hungary
from census_processor.india import India
from census_processor.indonesia import Indonesia
from census_processor.ireland import Ireland
from census_processor.italy import Italy
from census_processor.kazakhstan import Kazakhstan
from census_processor.latvia import Latvia
from census_processor.lithuania import Lithuania
from census_processor.luxembourg import Luxembourg
from census_processor.malta import Malta
from census_processor.mexico import Mexico
from census_processor.mongolia import Mongolia
from census_processor.mozambique import Mozambique
from census_processor.namibia import Namibia
from census_processor.netherlands import Netherlands
from census_processor.pakistan import Pakistan
from census_processor.poland import Poland
from census_processor.portugal import Portugal
from census_processor.romania import Romania
from census_processor.russia import Russia
from census_processor.saudi_arabia import SaudiArabia
from census_processor.slovakia import Slovakia
from census_processor.slovenia import Slovenia
from census_processor.south_africa import SouthAfrica
from census_processor.spain import Spain
from census_processor.sweden import Sweden
from census_processor.tanzania import Tanzania
from census_processor.turkey import Turkey
from census_processor.uganda import Uganda
from census_processor.uk import UK
from census_processor.ukraine import Ukraine
from census_processor.usa import USA
