path_dir:
  base: 'outputs/'
  model: 'models/saved_models/all_correct_to_FAO_scale_itr3_fr_0/'  # model weights to be loaded (Default: null)
  agland_map_output: 'outputs/all_correct_to_FAO_scale_itr3_fr_0/agland_map_output.tif'
  census_table_input: 'outputs/all_correct_to_FAO_scale_itr3_fr_0/processed_census.pkl'

# Land cover feature indices to be removed
# Note: this must match model
feature_remove: []  # []

# Bias correction
post_process:

  # disable_pycno: False
  disable_pycno: True
  correction:
    itr: 3
    method: 'scale'
    criteria: 'area' # 'percentage' or 'area'

    # force < threshold to be 0
    force_zero:
      switch: [True, True, False]     # turn on/off at the end of each iteration
      threshold: 0.00   # 0.015

    mask: 
      switch: [True, True, True]

      water_body_mask: 'land_cover/water_body_mask.tif'
      gdd_filter_mask: 'gdd/gdd_filter_map_360x720.tif'
      antarctica_mask: 'land_cover/antarctica_mask.tif'
      # aridity_mask: 'land_cover/aridity_masks/aridity_mask_thAEI_0.01_thAI_003.tif'
      aridity_mask: 'land_cover/aridity_masks/aridity_mask_thAEI_0.01_thAI_005.tif'
      australia_cropland_mask: 'land_cover/AgProbabilitySurfaces_2015_16/australia_cropland_mask.tif'
      australia_pasture_mask: 'land_cover/AgProbabilitySurfaces_2015_16/australia_pasture_mask.tif'

  # if disable_pycno, the following will not be used
  interpolation:
    seperable_filter: [0.5, 0, 0.5]
    # seperable_filter: [0.2, 0.2, 0.2, 0.2, 0.2]
    converge: 3
    r: 0.2  # relaxation
