path_dir:
  base: 'outputs/'
  model: 'models/saved_models/all_correct_to_FAO_scale_itr3_fr_0/invalid_scaled/GBM_model_python_1675836440840_1'  # model weights to be loaded (Default: null)
  agland_map_output: 'outputs/all_correct_to_FAO_scale_itr3_fr_0/agland_map_output.tif'
  census_table_input: 'outputs/all_correct_to_FAO_scale_itr3_fr_0/processed_census.pkl'

# Land cover feature indices to be removed
# Note: this must match model
feature_remove: []  # []

# Bias correction
post_process:

  disable_pycno: True

  correction:
    itr: 3
    method: 'scale'
    force_zero: True  # force < threshold to be 0
    threshold: 0.015   # 0.015

  # if disable_pycno, the following will not be used
  interpolation:
    seperable_filter: [0.5, 0, 0.5]
    # seperable_filter: [0.2, 0.2, 0.2, 0.2, 0.2]
    converge: 3
    r: 0.2  # relaxation
