path_dir:
  inputs:
    census_table_input: 'outputs/all_correct_to_FAO_scale_itr3_fr_0/processed_census.pkl'
    load_model: null  # model weights to be loaded (Default: null)

  outputs:
    save_model: 'models/saved_models/all_correct_to_FAO_scale_itr3_fr_0/'  # path to save model params
    pred_vs_ground_truth_fig: 'docs/source/_static/img/model_outputs/pred_vs_ground_truth_fig.png'  # null

model:
  gradient_boosting_tree:
    ntrees: 75
    max_depth: 6
    min_rows: 5
    learn_rate: 0.05
    sample_rate: 1.0
    col_sample_rate: 0.5
    nfolds: 0  # during evaluation

# Land cover feature indices to be removed from training
# Note: this must match load_model if specified
feature_remove: []  # []

# Outliers Handle
invalid_data_handle: 'scale'  # remove
